name: flutter_boilerplate_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  arna_logger: ^1.0.7
  go_router: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
