name: flutter_boilerplate_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Manager
  provider: ^6.0.5
  safe_change_notifier: ^0.3.1

  # Routing
  go_router: ^9.1.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Internationalization and Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Logger
  arna_logger: ^1.1.0

  # Draw SVG files
  flutter_svg: ^2.0.7

  # Load and cache network images
  cached_network_image: ^3.2.3

  # Code generation for models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Native splash screen
  flutter_native_splash: ^2.3.1

  # Web service
  arna_web_service: ^1.8.0

  # Dependency Injection
  get_it: ^7.6.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/translations/
